def helpy():
    print('Olá.')
    print()
    print('Aqui segue as informações detalhadas sobre cada comando da ferramenta.')
    print('OBS: No primeiro uso da ferramenta é necessario executar o comando 0 e 1. Uma vez importado os arquivos não sera necessário executar novamente o comando 1, lembre-se de sempre deixar o servidor rodando. ;] ')
    print()
    print('Comando 0: python3 initserver.py ')
    print("            -> Inicia o servidor da aplicação em modo escuta, aconselhavel rodar em um bash diferente, o servidor é necessario para importação dos arquivos e execução do algoritmo genético.")
    print()
    print('Comando 1: python3 main.py import disciplines.csv horarios.csv salas.csv')
    print("           -> Realiza a importação dos arquivos listados acima, defina a variavel de ambiente SERVER_SAVE_DIRECTORY de diretorio padrão e coloque seus arquivos lá, de acordo com os seus respectivos nomes e sequência")
    print()
    print('Comando 2: python3 main.py -i 100 -g 500 -m 0.10 -c 2')
    print("           -> Executa o algoritmo genético, é necessario importar os arquivos e carregar as configurações")
    print("           -> Configurações: (i = Número de individuos,g = Número de gerações,m = taxa de mutação,c = cruzamento)")
    print("           -> Ao final da execução será exportado o melhor quadro gerado, como também o gráfico de acompanhamento de valores e um arquivo .txt com informações do tempo de execução dada as configurações.")
    print()
    print()

