def helpy():
    print('Olá.')
    print()
    print('Aqui segue as informações detalhadas sobre cada comando da ferramenta.')
    print()
    print('Comando 0: python3 initserver.py ')
    print("            -> Inicia o servidor da aplicação, aconselhavel rodar em um bash diferente, o servidor é necessario para importação dos arquivos.")
    print()
    print('Comando 1: python3 main.py import disciplines.csv horarios.csv salas.csv')
    print("           -> Realiza a importação dos arquivos listados acima, defina a variavel de ambiente SERVER_SAVE_DIRECTORY de diretorio padrão e coloque seus arquivos lá, de acordo com os seus respectivos nomes e sequência")
    print()
    print('Comando 2: python3 main.py run')
    print("           -> Executa o algoritmo genético, é necessario importar os arquivos e carregar as configurações")
    print("           -> Configurações: (Número de individuos,Número de gerações,taxa de mutação,cruzamento)")
    print("           -> Ao final da execução será exportado o melhor quadro gerado, como também o gráfico de acompanhamento de valores.")
    print()
    print()
