import os

# CONFIGURATION PATH ARCHIVES JSON 
SERVER_DIRECTORY_SAVE = os.environ.get('SERVER_DIRECTORY_SAVE', 'DONT FOUND SERVER DIRECTORY PATH SAVE JSON OBJECTS INPUT')


FOLDER_INPUT='folders_kitkat/'
ARCHIVE_JSON_DISCIPLINES='disciplines.txt'
ARCHIVE_JSON_HORARIOS='horarios.txt'
ARCHIVE_JSON_SALAS='salas.txt'