# Generated by Django 3.0.3 on 2020-06-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(max_length=255, verbose_name='descricao')),
                ('rate', models.IntegerField(verbose_name='peso')),
            ],
            options={
                'verbose_name': 'Critério',
                'verbose_name_plural': 'Critérios',
                'ordering': ['rate'],
            },
        ),
    ]
