# Generated by Django 3.0.3 on 2020-06-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criterion',
        ),
    ]
