# Generated by Django 3.0.3 on 2020-06-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitkat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitKatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='email')),
                ('is_staff', models.BooleanField(verbose_name='admin')),
            ],
            options={
                'verbose_name': 'Kitkat User',
                'verbose_name_plural': 'Kitkat Users',
                'ordering': ['username'],
            },
        ),
    ]
